// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nidbmbdxecvwcrhvskkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pZGJtYmR4ZWN2d2NyaHZza2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4Nzk0MzMsImV4cCI6MjA2MTQ1NTQzM30.K4zloJtr2ATUdZNTInsEo3G4-7toyjM_AB9kiJjuxUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);